# Generated by Django 5.2.8 on 2025-12-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('ghost', 'Ghost Story'), ('temple', 'Temple Legend'), ('tribe', 'Tribal Story'), ('nature', 'Nature&Mountain Legends'), ('folklore', 'Local Folklore')], max_length=50),
        ),
    ]
