# Generated by Django 5.2.8 on 2025-12-11 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_story_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='content',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='custom_story_id',
            field=models.CharField(default='temp-id', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(default='stories/default.jpg', upload_to='stories/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
