# Generated by Django 5.2.8 on 2025-12-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_content_image_remove_content_submitted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='custom_story_id',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
