# Generated by Django 5.2.8 on 2025-12-14 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_alter_story_category_alter_story_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.RemoveField(
            model_name='story',
            name='custom_story_id',
        ),
        migrations.AddField(
            model_name='story',
            name='source',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
