# Generated by Django 5.2.8 on 2025-12-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_delete_content_remove_story_custom_story_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_images/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='source',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User')], default='system', max_length=20),
        ),
    ]
