# Generated by Django 5.2.7 on 2026-02-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0009_story_is_approved_alter_story_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
