# Generated by Django 5.2.7 on 2026-03-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0012_story_full_story_ml_story_title_ml_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='full_story_ml',
        ),
        migrations.RemoveField(
            model_name='story',
            name='title_ml',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
